platform:ios,'8.0'
target 'YSKJ' do
pod 'FMDB','~>2.6.2'
pod 'AFNetworking','~>3.1.0'
pod 'SDAutoLayout','~>2.1.3'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'MJRefresh','~>3.1.12'
pod 'Qiniu', '~> 7.1.2'
pod 'AGGeometryKit+POP', '~> 0.1'
pod 'MJExtension'
end
